export type GetApiRequestsRemaining = { getApiRequestsRemaining: number };

export type PodcastSeries = {
  uuid: string;
  datePublished: number;
  name: string;
  description: string;
  descriptionLinks: string[];
  imageUrl: string;
  itunesId: number;
  hash: string;
  childrenHash: string;
  episodes: PodcastEpisode[];
  totalEpisodesCount: number;
  genres: (keyof typeof Genre)[];
  itunesInfo: iTunesInfo;
  seriesType: keyof typeof PodcastSeriesType;
  language: keyof typeof Language;
  contentType: keyof typeof PodcastContentType;
  isExplicitContent: boolean;
  copyright: string;
  websiteUrl: string;
  rssUrl: string;
  rssOwnerName: string;
  rssOwnerPublicEmail: string;
  authorName: string;
  feedRefreshDetails: FeedRefreshDetails;
  taddyTranscribeStatus: keyof typeof PodcastSeriesTranscriptionStatus;
  popularityRank: keyof typeof PopularityRank;
  persons: Person[];
  isCompleted: boolean;
  isBlocked: boolean;
  isFavorite: boolean;
};

export type PodcastEpisode = {
  uuid: string;
  datePublished: number;
  name: string;
  description: string;
  descriptionLinks: string[];
  imageUrl: string;
  hash: string;
  guid: string;
  subtitle: string;
  audioUrl: string;
  videoUrl: string;
  fileLength: number;
  fileType: string;
  duration: number;
  episodeType: keyof typeof PodcastEpisodeType;
  seasonNumber: number;
  episodeNumber: number;
  websiteUrl: string;
  persons: Person[];
  taddyTranscribeStatus: keyof typeof PodcastEpisodeTranscriptionStatus;
  transcript: string[];
  transcriptWithSpeakersAndTimecodes: TranscriptItem[];
  transcriptUrls: string[];
  transcriptUrlsWithDetails: TranscriptLink[];
  chapters: Chapter[];
  chaptersUrls: string[];
  chaptersUrlsWithDetails: ChapterLink[];
  podcastSeries: PodcastSeries;
};

export type iTunesInfo = {
  uuid: string;
  hash: string;
  subtitle: string;
  summary: string;
  baseArtworkUrl: string;
  baseArtworkUrlOf: string;
  publisherId: number;
  publisherName: string;
  country: keyof typeof Country;
  podcastSeries: PodcastSeries;
};

export type WebsubDetails = {
  uuid: string;
  topicUrl: string;
  websubHubUrl: string;
  isVerified: boolean;
};

export type FeedRefreshDetails = {
  uuid: string;
  priority: keyof typeof FeedRefreshPriority;
  priorityReason: keyof typeof FeedRefreshPriorityReason;
  dateLastRefreshed: number;
  websubDetails: WebsubDetails;
};

export type Person = {
  uuid: string;
  name: string;
  role: keyof typeof ContentRole;
  url: string;
  imageUrl: string;
};

export type TranscriptItem = {
  id: string;
  text: string;
  speaker: string;
  startTimecode: number;
  endTimecode: number;
};

export type TranscriptLink = {
  url: string;
  type: string;
  isTaddyExclusive: boolean;
  language: string;
  hasTimecodes: boolean;
};

export type Chapter = {
  id: string;
  title: string;
  startTimecode: number;
};

export type ChapterLink = {
  url: string;
  type: string;
  isTaddyExclusive: boolean;
};

export type SearchRankingDetails = {
  id: string;
  uuid: string;
  type: keyof typeof SearchContentType;
  rankingScore: number;
};

export type SearchResponseDetails = {
  id: string;
  type: keyof typeof SearchContentType;
  totalCount: number;
  pagesCount: number;
};

export enum PodcastEpisodeType {
  FULL = "FULL",
  TRAILER = "TRAILER",
  BONUS = "BONUS",
}

export enum PodcastEpisodeTranscriptionStatus {
  NOT_TRANSCRIBING = "NOT_TRANSCRIBING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

enum FeedRefreshPriority {
  WEBSUB = "WEBSUB",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  REGULAR = "REGULAR",
  LOW = "LOW",
  INACTIVE = "INACTIVE",
  NEVER = "NEVER",
}

export enum PodcastSeriesTranscriptionStatus {
  TRANSCRIBING = "TRANSCRIBING",
  NOT_TRANSCRIBING = "NOT_TRANSCRIBING",
  CREATOR_ASKED_NOT_TO_TRANSCRIBE = "CREATOR_ASKED_NOT_TO_TRANSCRIBE",
}

export enum FeedRefreshPriorityReason {
  INACTIVE_FOR_OVER_1_YEAR = "INACTIVE_FOR_OVER_1_YEAR",
  DUPLICATE_FEED = "DUPLICATE_FEED",
  ERROR_PARSING_FEED = "ERROR_PARSING_FEED",
  FEED_URL_NOT_WORKING = "FEED_URL_NOT_WORKING",
  PRIVATE_PODCAST_FEED = "PRIVATE_PODCAST_FEED",
  VIOLATES_TADDY_DISTRIBUTION_POLICY = "VIOLATES_TADDY_DISTRIBUTION_POLICY",
}

export enum PopularityRank {
  TOP_200 = "TOP_200",
  TOP_1000 = "TOP_1000",
  TOP_2000 = "TOP_2000",
  TOP_3000 = "TOP_3000",
  TOP_4000 = "TOP_4000",
  TOP_5000 = "TOP_5000",
  TOP_10000 = "TOP_10000",
  TOP_20000 = "TOP_20000",
  TOP_50000 = "TOP_50000",
  TOP_100000 = "TOP_100000",
  TOP_200000 = "TOP_200000",
}

export enum ContentRole {
  PODCASTSERIES_DIRECTOR = "PODCASTSERIES_DIRECTOR",
  PODCASTSERIES_ASSISTANT_DIRECTOR = "PODCASTSERIES_ASSISTANT_DIRECTOR",
  PODCASTSERIES_EXECUTIVE_PRODUCER = "PODCASTSERIES_EXECUTIVE_PRODUCER",
  PODCASTSERIES_SENIOR_PRODUCER = "PODCASTSERIES_SENIOR_PRODUCER",
  PODCASTSERIES_PRODUCER = "PODCASTSERIES_PRODUCER",
  PODCASTSERIES_ASSOCIATE_PRODUCER = "PODCASTSERIES_ASSOCIATE_PRODUCER",
  PODCASTSERIES_DEVELOPMENT_PRODUCER = "PODCASTSERIES_DEVELOPMENT_PRODUCER",
  PODCASTSERIES_CREATIVE_DIRECTOR = "PODCASTSERIES_CREATIVE_DIRECTOR",
  PODCASTSERIES_HOST = "PODCASTSERIES_HOST",
  PODCASTSERIES_CO_HOST = "PODCASTSERIES_CO_HOST",
  PODCASTSERIES_GUEST_HOST = "PODCASTSERIES_GUEST_HOST",
  PODCASTSERIES_GUEST = "PODCASTSERIES_GUEST",
  PODCASTSERIES_VOICE_ACTOR = "PODCASTSERIES_VOICE_ACTOR",
  PODCASTSERIES_NARRATOR = "PODCASTSERIES_NARRATOR",
  PODCASTSERIES_ANNOUNCER = "PODCASTSERIES_ANNOUNCER",
  PODCASTSERIES_REPORTER = "PODCASTSERIES_REPORTER",
  PODCASTSERIES_AUTHOR = "PODCASTSERIES_AUTHOR",
  PODCASTSERIES_EDITORIAL_DIRECTOR = "PODCASTSERIES_EDITORIAL_DIRECTOR",
  PODCASTSERIES_CO_WRITER = "PODCASTSERIES_CO_WRITER",
  PODCASTSERIES_WRITER = "PODCASTSERIES_WRITER",
  PODCASTSERIES_SONGWRITER = "PODCASTSERIES_SONGWRITER",
  PODCASTSERIES_GUEST_WRITER = "PODCASTSERIES_GUEST_WRITER",
  PODCASTSERIES_STORY_EDITOR = "PODCASTSERIES_STORY_EDITOR",
  PODCASTSERIES_MANAGING_EDITOR = "PODCASTSERIES_MANAGING_EDITOR",
  PODCASTSERIES_SCRIPT_EDITOR = "PODCASTSERIES_SCRIPT_EDITOR",
  PODCASTSERIES_SCRIPT_COORDINATOR = "PODCASTSERIES_SCRIPT_COORDINATOR",
  PODCASTSERIES_RESEARCHER = "PODCASTSERIES_RESEARCHER",
  PODCASTSERIES_EDITOR = "PODCASTSERIES_EDITOR",
  PODCASTSERIES_FACT_CHECKER = "PODCASTSERIES_FACT_CHECKER",
  PODCASTSERIES_TRANSLATOR = "PODCASTSERIES_TRANSLATOR",
  PODCASTSERIES_TRANSCRIBER = "PODCASTSERIES_TRANSCRIBER",
  PODCASTSERIES_LOGGER = "PODCASTSERIES_LOGGER",
  PODCASTSERIES_STUDIO_COORDINATOR = "PODCASTSERIES_STUDIO_COORDINATOR",
  PODCASTSERIES_TECHNICAL_DIRECTOR = "PODCASTSERIES_TECHNICAL_DIRECTOR",
  PODCASTSERIES_TECHNICAL_MANAGER = "PODCASTSERIES_TECHNICAL_MANAGER",
  PODCASTSERIES_AUDIO_ENGINEER = "PODCASTSERIES_AUDIO_ENGINEER",
  PODCASTSERIES_REMOTE_RECORDING_ENGINEER = "PODCASTSERIES_REMOTE_RECORDING_ENGINEER",
  PODCASTSERIES_POST_PRODUCTION_ENGINEER = "PODCASTSERIES_POST_PRODUCTION_ENGINEER",
  PODCASTSERIES_AUDIO_EDITOR = "PODCASTSERIES_AUDIO_EDITOR",
  PODCASTSERIES_SOUND_DESIGNER = "PODCASTSERIES_SOUND_DESIGNER",
  PODCASTSERIES_FOLEY_ARTIST = "PODCASTSERIES_FOLEY_ARTIST",
  PODCASTSERIES_COMPOSER = "PODCASTSERIES_COMPOSER",
  PODCASTSERIES_THEME_MUSIC = "PODCASTSERIES_THEME_MUSIC",
  PODCASTSERIES_MUSIC_PRODUCTION = "PODCASTSERIES_MUSIC_PRODUCTION",
  PODCASTSERIES_MUSIC_CONTRIBUTOR = "PODCASTSERIES_MUSIC_CONTRIBUTOR",
  PODCASTSERIES_PRODUCTION_COORDINATOR = "PODCASTSERIES_PRODUCTION_COORDINATOR",
  PODCASTSERIES_BOOKING_COORDINATOR = "PODCASTSERIES_BOOKING_COORDINATOR",
  PODCASTSERIES_PRODUCTION_ASSISTANT = "PODCASTSERIES_PRODUCTION_ASSISTANT",
  PODCASTSERIES_CONTENT_MANAGER = "PODCASTSERIES_CONTENT_MANAGER",
  PODCASTSERIES_MARKETING_MANAGER = "PODCASTSERIES_MARKETING_MANAGER",
  PODCASTSERIES_SALES_REPRESENTATIVE = "PODCASTSERIES_SALES_REPRESENTATIVE",
  PODCASTSERIES_SALES_MANAGER = "PODCASTSERIES_SALES_MANAGER",
  PODCASTSERIES_GRAPHIC_DESIGNER = "PODCASTSERIES_GRAPHIC_DESIGNER",
  PODCASTSERIES_COVER_ART_DESIGNER = "PODCASTSERIES_COVER_ART_DESIGNER",
  PODCASTSERIES_SOCIAL_MEDIA_MANAGER = "PODCASTSERIES_SOCIAL_MEDIA_MANAGER",
  PODCASTSERIES_MISC_CONSULTANT = "PODCASTSERIES_MISC_CONSULTANT",
  PODCASTSERIES_MISC_INTERN = "PODCASTSERIES_MISC_INTERN",
  PODCASTSERIES_CAMERA_OPERATOR = "PODCASTSERIES_CAMERA_OPERATOR",
  PODCASTSERIES_LIGHTING_DESIGNER = "PODCASTSERIES_LIGHTING_DESIGNER",
  PODCASTSERIES_CAMERA_GRIP = "PODCASTSERIES_CAMERA_GRIP",
  PODCASTSERIES_ASSISTANT_CAMERA = "PODCASTSERIES_ASSISTANT_CAMERA",
  PODCASTSERIES_ASSISTANT_EDITOR = "PODCASTSERIES_ASSISTANT_EDITOR",
}

export enum TranscriptItemStyle {
  UTTERANCE = "UTTERANCE",
  PARAGRAPH = "PARAGRAPH",
}

export enum Language {
  ABKHAZIAN = "ABKHAZIAN",
  AFAR = "AFAR",
  AFRIKAANS = "AFRIKAANS",
  AKAN = "AKAN",
  ALBANIAN = "ALBANIAN",
  AMHARIC = "AMHARIC",
  ARABIC = "ARABIC",
  ARAGONESE = "ARAGONESE",
  ARMENIAN = "ARMENIAN",
  ASSAMESE = "ASSAMESE",
  AVARIC = "AVARIC",
  AVESTAN = "AVESTAN",
  AYMARA = "AYMARA",
  AZERBAIJANI = "AZERBAIJANI",
  BAMBARA = "BAMBARA",
  BASHKIR = "BASHKIR",
  BASQUE = "BASQUE",
  BELARUSIAN = "BELARUSIAN",
  BENGALI = "BENGALI",
  BIHARI_LANGUAGES = "BIHARI_LANGUAGES",
  BISLAMA = "BISLAMA",
  BOSNIAN = "BOSNIAN",
  BRETON = "BRETON",
  BULGARIAN = "BULGARIAN",
  BURMESE = "BURMESE",
  CENTRAL_KHMER = "CENTRAL_KHMER",
  CHINESE = "CHINESE",
  CHURCH_SLAVONIC = "CHURCH_SLAVONIC",
  CHUVASH = "CHUVASH",
  CORNISH = "CORNISH",
  CORSICAN = "CORSICAN",
  CREE = "CREE",
  CROATIAN = "CROATIAN",
  CZECH = "CZECH",
  DANISH = "DANISH",
  DHIVEHI_MALDIVIAN = "DHIVEHI_MALDIVIAN",
  DUTCH_FLEMISH = "DUTCH_FLEMISH",
  DZONGKHA = "DZONGKHA",
  ENGLISH = "ENGLISH",
  ESPERANTO = "ESPERANTO",
  ESTONIAN = "ESTONIAN",
  EWE = "EWE",
  FAROESE = "FAROESE",
  FARSI = "FARSI",
  FIJIAN = "FIJIAN",
  FINNISH = "FINNISH",
  FRENCH = "FRENCH",
  FULAH = "FULAH",
  GAELIC = "GAELIC",
  GALICIAN = "GALICIAN",
  GANDA = "GANDA",
  GEORGIAN = "GEORGIAN",
  GERMAN = "GERMAN",
  GIKUYU = "GIKUYU",
  GREEK = "GREEK",
  GUARANI = "GUARANI",
  GUJARATI = "GUJARATI",
  HAITIAN_CREOLE = "HAITIAN_CREOLE",
  HAUSA = "HAUSA",
  HEBREW = "HEBREW",
  HERERO = "HERERO",
  HINDI = "HINDI",
  HIRI_MOTU = "HIRI_MOTU",
  HUNGARIAN = "HUNGARIAN",
  ICELANDIC = "ICELANDIC",
  IDO = "IDO",
  IGBO = "IGBO",
  INDONESIAN = "INDONESIAN",
  INTERLINGUA = "INTERLINGUA",
  INTERLINGUE_OCCIDENTAL = "INTERLINGUE_OCCIDENTAL",
  INUKTITUT = "INUKTITUT",
  INUPIAQ = "INUPIAQ",
  IRISH = "IRISH",
  ITALIAN = "ITALIAN",
  JAPANESE = "JAPANESE",
  JAVANESE = "JAVANESE",
  KALAALLISUT_GREENLANDIC = "KALAALLISUT_GREENLANDIC",
  KANNADA = "KANNADA",
  KANURI = "KANURI",
  KASHMIRI = "KASHMIRI",
  KAZAKH = "KAZAKH",
  KINYARWANDA = "KINYARWANDA",
  KOMI = "KOMI",
  KONGO = "KONGO",
  KOREAN = "KOREAN",
  KURDISH = "KURDISH",
  KWANYAMA = "KWANYAMA",
  KYRGYZ = "KYRGYZ",
  LAO = "LAO",
  LATIN = "LATIN",
  LATVIAN = "LATVIAN",
  LETZEBURGESCH = "LETZEBURGESCH",
  LIMBURGISH = "LIMBURGISH",
  LINGALA = "LINGALA",
  LITHUANIAN = "LITHUANIAN",
  LUBA_KATANGA = "LUBA_KATANGA",
  MACEDONIAN = "MACEDONIAN",
  MALAGASY = "MALAGASY",
  MALAY = "MALAY",
  MALAYALAM = "MALAYALAM",
  MALTESE = "MALTESE",
  MANX = "MANX",
  MAORI = "MAORI",
  MARATHI = "MARATHI",
  MARSHALLESE = "MARSHALLESE",
  MONGOLIAN = "MONGOLIAN",
  NAURU = "NAURU",
  NAVAJO = "NAVAJO",
  NDONGA = "NDONGA",
  NEPALI = "NEPALI",
  NORTH_NDEBELE = "NORTH_NDEBELE",
  NORTHERN_SAMI = "NORTHERN_SAMI",
  NORWEGIAN = "NORWEGIAN",
  NORWEGIAN_BOKMAL = "NORWEGIAN_BOKMAL",
  NORWEGIAN_NYNORSK = "NORWEGIAN_NYNORSK",
  NUOSU_SICHUAN_YI = "NUOSU_SICHUAN_YI",
  OCCITAN = "OCCITAN",
  OJIBWA = "OJIBWA",
  ORIYA = "ORIYA",
  OROMO = "OROMO",
  OSSETIAN = "OSSETIAN",
  PALI = "PALI",
  PASHTO = "PASHTO",
  POLISH = "POLISH",
  PORTUGUESE = "PORTUGUESE",
  PUNJABI = "PUNJABI",
  QUECHUA = "QUECHUA",
  ROMANIAN_MOLDOVAN = "ROMANIAN_MOLDOVAN",
  ROMANSH = "ROMANSH",
  RUNDI = "RUNDI",
  RUSSIAN = "RUSSIAN",
  SAMOAN = "SAMOAN",
  SANGO = "SANGO",
  SANSKRIT = "SANSKRIT",
  SARDINIAN = "SARDINIAN",
  SERBIAN = "SERBIAN",
  SHONA = "SHONA",
  SINDHI = "SINDHI",
  SINHALA = "SINHALA",
  SLOVAK = "SLOVAK",
  SLOVENIAN = "SLOVENIAN",
  SOMALI = "SOMALI",
  SOTHO = "SOTHO",
  SOUTH_NDEBELE = "SOUTH_NDEBELE",
  SPANISH = "SPANISH",
  SUNDANESE = "SUNDANESE",
  SWAHILI = "SWAHILI",
  SWATI = "SWATI",
  SWEDISH = "SWEDISH",
  TAGALOG = "TAGALOG",
  TAHITIAN = "TAHITIAN",
  TAJIK = "TAJIK",
  TAMIL = "TAMIL",
  TATAR = "TATAR",
  TELUGU = "TELUGU",
  THAI = "THAI",
  TIBETAN = "TIBETAN",
  TIGRINYA = "TIGRINYA",
  TONGA = "TONGA",
  TSONGA = "TSONGA",
  TSWANA = "TSWANA",
  TURKISH = "TURKISH",
  TURKMEN = "TURKMEN",
  TWI = "TWI",
  UKRAINIAN = "UKRAINIAN",
  URDU = "URDU",
  UYGHUR = "UYGHUR",
  UZBEK = "UZBEK",
  VALENCIAN_CATALAN = "VALENCIAN_CATALAN",
  VENDA = "VENDA",
  VIETNAMESE = "VIETNAMESE",
  VOLAPUK = "VOLAPUK",
  WALLOON = "WALLOON",
  WELSH = "WELSH",
  WESTERN_FRISIAN = "WESTERN_FRISIAN",
  WOLOF = "WOLOF",
  XHOSA = "XHOSA",
  YIDDISH = "YIDDISH",
  YORUBA = "YORUBA",
  ZHUANG = "ZHUANG",
  ZULU = "ZULU",
}

export enum SortOrder {
  LATEST = "LATEST",
  OLDEST = "OLDEST",
  SEARCH = "SEARCH",
}

export enum PodcastSeriesType {
  EPISODIC = "EPISODIC",
  SERIAL = "SERIAL",
}

export enum PodcastContentType {
  AUDIO = "AUDIO",
  VIDEO = "VIDEO",
}

export enum Genre {
  PODCASTSERIES_ARTS = "PODCASTSERIES_ARTS",
  PODCASTSERIES_ARTS_BOOKS = "PODCASTSERIES_ARTS_BOOKS",
  PODCASTSERIES_ARTS_DESIGN = "PODCASTSERIES_ARTS_DESIGN",
  PODCASTSERIES_ARTS_FASHION_AND_BEAUTY = "PODCASTSERIES_ARTS_FASHION_AND_BEAUTY",
  PODCASTSERIES_ARTS_FOOD = "PODCASTSERIES_ARTS_FOOD",
  PODCASTSERIES_ARTS_PERFORMING_ARTS = "PODCASTSERIES_ARTS_PERFORMING_ARTS",
  PODCASTSERIES_ARTS_VISUAL_ARTS = "PODCASTSERIES_ARTS_VISUAL_ARTS",
  PODCASTSERIES_BUSINESS = "PODCASTSERIES_BUSINESS",
  PODCASTSERIES_BUSINESS_CAREERS = "PODCASTSERIES_BUSINESS_CAREERS",
  PODCASTSERIES_BUSINESS_ENTREPRENEURSHIP = "PODCASTSERIES_BUSINESS_ENTREPRENEURSHIP",
  PODCASTSERIES_BUSINESS_INVESTING = "PODCASTSERIES_BUSINESS_INVESTING",
  PODCASTSERIES_BUSINESS_MANAGEMENT = "PODCASTSERIES_BUSINESS_MANAGEMENT",
  PODCASTSERIES_BUSINESS_MARKETING = "PODCASTSERIES_BUSINESS_MARKETING",
  PODCASTSERIES_BUSINESS_NON_PROFIT = "PODCASTSERIES_BUSINESS_NON_PROFIT",
  PODCASTSERIES_COMEDY = "PODCASTSERIES_COMEDY",
  PODCASTSERIES_COMEDY_INTERVIEWS = "PODCASTSERIES_COMEDY_INTERVIEWS",
  PODCASTSERIES_COMEDY_IMPROV = "PODCASTSERIES_COMEDY_IMPROV",
  PODCASTSERIES_COMEDY_STANDUP = "PODCASTSERIES_COMEDY_STANDUP",
  PODCASTSERIES_EDUCATION = "PODCASTSERIES_EDUCATION",
  PODCASTSERIES_EDUCATION_COURSES = "PODCASTSERIES_EDUCATION_COURSES",
  PODCASTSERIES_EDUCATION_HOW_TO = "PODCASTSERIES_EDUCATION_HOW_TO",
  PODCASTSERIES_EDUCATION_LANGUAGE_LEARNING = "PODCASTSERIES_EDUCATION_LANGUAGE_LEARNING",
  PODCASTSERIES_EDUCATION_SELF_IMPROVEMENT = "PODCASTSERIES_EDUCATION_SELF_IMPROVEMENT",
  PODCASTSERIES_FICTION = "PODCASTSERIES_FICTION",
  PODCASTSERIES_FICTION_COMEDY_FICTION = "PODCASTSERIES_FICTION_COMEDY_FICTION",
  PODCASTSERIES_FICTION_DRAMA = "PODCASTSERIES_FICTION_DRAMA",
  PODCASTSERIES_FICTION_SCIENCE_FICTION = "PODCASTSERIES_FICTION_SCIENCE_FICTION",
  PODCASTSERIES_GOVERNMENT = "PODCASTSERIES_GOVERNMENT",
  PODCASTSERIES_HISTORY = "PODCASTSERIES_HISTORY",
  PODCASTSERIES_HEALTH_AND_FITNESS = "PODCASTSERIES_HEALTH_AND_FITNESS",
  PODCASTSERIES_HEALTH_AND_FITNESS_ALTERNATIVE_HEALTH = "PODCASTSERIES_HEALTH_AND_FITNESS_ALTERNATIVE_HEALTH",
  PODCASTSERIES_HEALTH_AND_FITNESS_FITNESS = "PODCASTSERIES_HEALTH_AND_FITNESS_FITNESS",
  PODCASTSERIES_HEALTH_AND_FITNESS_MEDICINE = "PODCASTSERIES_HEALTH_AND_FITNESS_MEDICINE",
  PODCASTSERIES_HEALTH_AND_FITNESS_MENTAL_HEALTH = "PODCASTSERIES_HEALTH_AND_FITNESS_MENTAL_HEALTH",
  PODCASTSERIES_HEALTH_AND_FITNESS_NUTRITION = "PODCASTSERIES_HEALTH_AND_FITNESS_NUTRITION",
  PODCASTSERIES_HEALTH_AND_FITNESS_SEXUALITY = "PODCASTSERIES_HEALTH_AND_FITNESS_SEXUALITY",
  PODCASTSERIES_KIDS_AND_FAMILY = "PODCASTSERIES_KIDS_AND_FAMILY",
  PODCASTSERIES_KIDS_AND_FAMILY_EDUCATION_FOR_KIDS = "PODCASTSERIES_KIDS_AND_FAMILY_EDUCATION_FOR_KIDS",
  PODCASTSERIES_KIDS_AND_FAMILY_PARENTING = "PODCASTSERIES_KIDS_AND_FAMILY_PARENTING",
  PODCASTSERIES_KIDS_AND_FAMILY_PETS_AND_ANIMALS = "PODCASTSERIES_KIDS_AND_FAMILY_PETS_AND_ANIMALS",
  PODCASTSERIES_KIDS_AND_FAMILY_STORIES_FOR_KIDS = "PODCASTSERIES_KIDS_AND_FAMILY_STORIES_FOR_KIDS",
  PODCASTSERIES_LEISURE = "PODCASTSERIES_LEISURE",
  PODCASTSERIES_LEISURE_ANIMATION_AND_MANGA = "PODCASTSERIES_LEISURE_ANIMATION_AND_MANGA",
  PODCASTSERIES_LEISURE_AUTOMOTIVE = "PODCASTSERIES_LEISURE_AUTOMOTIVE",
  PODCASTSERIES_LEISURE_AVIATION = "PODCASTSERIES_LEISURE_AVIATION",
  PODCASTSERIES_LEISURE_CRAFTS = "PODCASTSERIES_LEISURE_CRAFTS",
  PODCASTSERIES_LEISURE_GAMES = "PODCASTSERIES_LEISURE_GAMES",
  PODCASTSERIES_LEISURE_HOBBIES = "PODCASTSERIES_LEISURE_HOBBIES",
  PODCASTSERIES_LEISURE_HOME_AND_GARDEN = "PODCASTSERIES_LEISURE_HOME_AND_GARDEN",
  PODCASTSERIES_LEISURE_VIDEO_GAMES = "PODCASTSERIES_LEISURE_VIDEO_GAMES",
  PODCASTSERIES_MUSIC = "PODCASTSERIES_MUSIC",
  PODCASTSERIES_MUSIC_COMMENTARY = "PODCASTSERIES_MUSIC_COMMENTARY",
  PODCASTSERIES_MUSIC_HISTORY = "PODCASTSERIES_MUSIC_HISTORY",
  PODCASTSERIES_MUSIC_INTERVIEWS = "PODCASTSERIES_MUSIC_INTERVIEWS",
  PODCASTSERIES_NEWS = "PODCASTSERIES_NEWS",
  PODCASTSERIES_NEWS_BUSINESS = "PODCASTSERIES_NEWS_BUSINESS",
  PODCASTSERIES_NEWS_DAILY_NEWS = "PODCASTSERIES_NEWS_DAILY_NEWS",
  PODCASTSERIES_NEWS_ENTERTAINMENT = "PODCASTSERIES_NEWS_ENTERTAINMENT",
  PODCASTSERIES_NEWS_COMMENTARY = "PODCASTSERIES_NEWS_COMMENTARY",
  PODCASTSERIES_NEWS_POLITICS = "PODCASTSERIES_NEWS_POLITICS",
  PODCASTSERIES_NEWS_SPORTS = "PODCASTSERIES_NEWS_SPORTS",
  PODCASTSERIES_NEWS_TECH = "PODCASTSERIES_NEWS_TECH",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY_BUDDHISM = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_BUDDHISM",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY_CHRISTIANITY = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_CHRISTIANITY",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY_HINDUISM = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_HINDUISM",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY_ISLAM = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_ISLAM",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY_JUDAISM = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_JUDAISM",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY_RELIGION = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_RELIGION",
  PODCASTSERIES_RELIGION_AND_SPIRITUALITY_SPIRITUALITY = "PODCASTSERIES_RELIGION_AND_SPIRITUALITY_SPIRITUALITY",
  PODCASTSERIES_SCIENCE = "PODCASTSERIES_SCIENCE",
  PODCASTSERIES_SCIENCE_ASTRONOMY = "PODCASTSERIES_SCIENCE_ASTRONOMY",
  PODCASTSERIES_SCIENCE_CHEMISTRY = "PODCASTSERIES_SCIENCE_CHEMISTRY",
  PODCASTSERIES_SCIENCE_EARTH_SCIENCES = "PODCASTSERIES_SCIENCE_EARTH_SCIENCES",
  PODCASTSERIES_SCIENCE_LIFE_SCIENCES = "PODCASTSERIES_SCIENCE_LIFE_SCIENCES",
  PODCASTSERIES_SCIENCE_MATHEMATICS = "PODCASTSERIES_SCIENCE_MATHEMATICS",
  PODCASTSERIES_SCIENCE_NATURAL_SCIENCES = "PODCASTSERIES_SCIENCE_NATURAL_SCIENCES",
  PODCASTSERIES_SCIENCE_NATURE = "PODCASTSERIES_SCIENCE_NATURE",
  PODCASTSERIES_SCIENCE_PHYSICS = "PODCASTSERIES_SCIENCE_PHYSICS",
  PODCASTSERIES_SCIENCE_SOCIAL_SCIENCES = "PODCASTSERIES_SCIENCE_SOCIAL_SCIENCES",
  PODCASTSERIES_SOCIETY_AND_CULTURE = "PODCASTSERIES_SOCIETY_AND_CULTURE",
  PODCASTSERIES_SOCIETY_AND_CULTURE_DOCUMENTARY = "PODCASTSERIES_SOCIETY_AND_CULTURE_DOCUMENTARY",
  PODCASTSERIES_SOCIETY_AND_CULTURE_PERSONAL_JOURNALS = "PODCASTSERIES_SOCIETY_AND_CULTURE_PERSONAL_JOURNALS",
  PODCASTSERIES_SOCIETY_AND_CULTURE_PHILOSOPHY = "PODCASTSERIES_SOCIETY_AND_CULTURE_PHILOSOPHY",
  PODCASTSERIES_SOCIETY_AND_CULTURE_PLACES_AND_TRAVEL = "PODCASTSERIES_SOCIETY_AND_CULTURE_PLACES_AND_TRAVEL",
  PODCASTSERIES_SOCIETY_AND_CULTURE_RELATIONSHIPS = "PODCASTSERIES_SOCIETY_AND_CULTURE_RELATIONSHIPS",
  PODCASTSERIES_SPORTS = "PODCASTSERIES_SPORTS",
  PODCASTSERIES_SPORTS_BASEBALL = "PODCASTSERIES_SPORTS_BASEBALL",
  PODCASTSERIES_SPORTS_BASKETBALL = "PODCASTSERIES_SPORTS_BASKETBALL",
  PODCASTSERIES_SPORTS_CRICKET = "PODCASTSERIES_SPORTS_CRICKET",
  PODCASTSERIES_SPORTS_FANTASY_SPORTS = "PODCASTSERIES_SPORTS_FANTASY_SPORTS",
  PODCASTSERIES_SPORTS_FOOTBALL = "PODCASTSERIES_SPORTS_FOOTBALL",
  PODCASTSERIES_SPORTS_GOLF = "PODCASTSERIES_SPORTS_GOLF",
  PODCASTSERIES_SPORTS_HOCKEY = "PODCASTSERIES_SPORTS_HOCKEY",
  PODCASTSERIES_SPORTS_RUGBY = "PODCASTSERIES_SPORTS_RUGBY",
  PODCASTSERIES_SPORTS_RUNNING = "PODCASTSERIES_SPORTS_RUNNING",
  PODCASTSERIES_SPORTS_SOCCER = "PODCASTSERIES_SPORTS_SOCCER",
  PODCASTSERIES_SPORTS_SWIMMING = "PODCASTSERIES_SPORTS_SWIMMING",
  PODCASTSERIES_SPORTS_TENNIS = "PODCASTSERIES_SPORTS_TENNIS",
  PODCASTSERIES_SPORTS_VOLLEYBALL = "PODCASTSERIES_SPORTS_VOLLEYBALL",
  PODCASTSERIES_SPORTS_WILDERNESS = "PODCASTSERIES_SPORTS_WILDERNESS",
  PODCASTSERIES_SPORTS_WRESTLING = "PODCASTSERIES_SPORTS_WRESTLING",
  PODCASTSERIES_TECHNOLOGY = "PODCASTSERIES_TECHNOLOGY",
  PODCASTSERIES_TRUE_CRIME = "PODCASTSERIES_TRUE_CRIME",
  PODCASTSERIES_TV_AND_FILM = "PODCASTSERIES_TV_AND_FILM",
  PODCASTSERIES_TV_AND_FILM_AFTER_SHOWS = "PODCASTSERIES_TV_AND_FILM_AFTER_SHOWS",
  PODCASTSERIES_TV_AND_FILM_HISTORY = "PODCASTSERIES_TV_AND_FILM_HISTORY",
  PODCASTSERIES_TV_AND_FILM_INTERVIEWS = "PODCASTSERIES_TV_AND_FILM_INTERVIEWS",
  PODCASTSERIES_TV_AND_FILM_FILM_REVIEWS = "PODCASTSERIES_TV_AND_FILM_FILM_REVIEWS",
  PODCASTSERIES_TV_AND_FILM_TV_REVIEWS = "PODCASTSERIES_TV_AND_FILM_TV_REVIEWS",
}

export enum Country {
  AFGHANISTAN = "AFGHANISTAN",
  ALAND_ISLANDS = "ALAND_ISLANDS",
  ALBANIA = "ALBANIA",
  ALGERIA = "ALGERIA",
  AMERICAN_SAMOA = "AMERICAN_SAMOA",
  ANDORRA = "ANDORRA",
  ANGOLA = "ANGOLA",
  ANGUILLA = "ANGUILLA",
  ANTARCTICA = "ANTARCTICA",
  ANTIGUA_AND_BARBUDA = "ANTIGUA_AND_BARBUDA",
  ARGENTINA = "ARGENTINA",
  ARMENIA = "ARMENIA",
  ARUBA = "ARUBA",
  AUSTRALIA = "AUSTRALIA",
  AUSTRIA = "AUSTRIA",
  AZERBAIJAN = "AZERBAIJAN",
  BAHAMAS = "BAHAMAS",
  BAHRAIN = "BAHRAIN",
  BANGLADESH = "BANGLADESH",
  BARBADOS = "BARBADOS",
  BELARUS = "BELARUS",
  BELGIUM = "BELGIUM",
  BELIZE = "BELIZE",
  BENIN = "BENIN",
  BERMUDA = "BERMUDA",
  BHUTAN = "BHUTAN",
  BOLIVIA_PLURINATIONAL_STATE_OF = "BOLIVIA_PLURINATIONAL_STATE_OF",
  BONAIRE_SINT_EUSTATIUS_AND_SABA = "BONAIRE_SINT_EUSTATIUS_AND_SABA",
  BOSNIA_AND_HERZEGOVINA = "BOSNIA_AND_HERZEGOVINA",
  BOTSWANA = "BOTSWANA",
  BOUVET_ISLAND = "BOUVET_ISLAND",
  BRAZIL = "BRAZIL",
  BRITISH_INDIAN_OCEAN_TERRITORY_THE = "BRITISH_INDIAN_OCEAN_TERRITORY_THE",
  BRUNEI_DARUSSALAM = "BRUNEI_DARUSSALAM",
  BULGARIA = "BULGARIA",
  BURKINA_FASO = "BURKINA_FASO",
  BURUNDI = "BURUNDI",
  CABO_VERDE = "CABO_VERDE",
  CAMBODIA = "CAMBODIA",
  CAMEROON = "CAMEROON",
  CANADA = "CANADA",
  CAYMAN_ISLANDS = "CAYMAN_ISLANDS",
  CENTRAL_AFRICAN_REPUBLIC = "CENTRAL_AFRICAN_REPUBLIC",
  CHAD = "CHAD",
  CHILE = "CHILE",
  CHINA = "CHINA",
  CHRISTMAS_ISLAND = "CHRISTMAS_ISLAND",
  COCOS_KEELING_ISLANDS = "COCOS_KEELING_ISLANDS",
  COLOMBIA = "COLOMBIA",
  COMOROS = "COMOROS",
  CONGO = "CONGO",
  CONGO_THE_DEMOCRATIC_REPUBLIC_OF = "CONGO_THE_DEMOCRATIC_REPUBLIC_OF",
  COOK_ISLANDS = "COOK_ISLANDS",
  COSTA_RICA = "COSTA_RICA",
  COTE_D_IVOIRE = "COTE_D_IVOIRE",
  CROATIA = "CROATIA",
  CUBA = "CUBA",
  CURACAO = "CURACAO",
  CYPRUS = "CYPRUS",
  CZECHIA = "CZECHIA",
  DENMARK = "DENMARK",
  DJIBOUTI = "DJIBOUTI",
  DOMINICA = "DOMINICA",
  DOMINICAN_REPUBLIC = "DOMINICAN_REPUBLIC",
  ECUADOR = "ECUADOR",
  EGYPT = "EGYPT",
  EL_SALVADOR = "EL_SALVADOR",
  EQUATORIAL_GUINEA = "EQUATORIAL_GUINEA",
  ERITREA = "ERITREA",
  ESTONIA = "ESTONIA",
  ESWATINI = "ESWATINI",
  ETHIOPIA = "ETHIOPIA",
  FALKLAND_ISLANDS_THE_MALVINAS = "FALKLAND_ISLANDS_THE_MALVINAS",
  FAROE_ISLANDS = "FAROE_ISLANDS",
  FIJI = "FIJI",
  FINLAND = "FINLAND",
  FRANCE = "FRANCE",
  FRENCH_GUIANA = "FRENCH_GUIANA",
  FRENCH_POLYNESIA = "FRENCH_POLYNESIA",
  FRENCH_SOUTHERN_TERRITORIES = "FRENCH_SOUTHERN_TERRITORIES",
  GABON = "GABON",
  GAMBIA = "GAMBIA",
  GEORGIA = "GEORGIA",
  GERMANY = "GERMANY",
  GHANA = "GHANA",
  GIBRALTAR = "GIBRALTAR",
  GREECE = "GREECE",
  GREENLAND = "GREENLAND",
  GRENADA = "GRENADA",
  GUADELOUPE = "GUADELOUPE",
  GUAM = "GUAM",
  GUATEMALA = "GUATEMALA",
  GUERNSEY = "GUERNSEY",
  GUINEA = "GUINEA",
  GUINEA_BISSAU = "GUINEA_BISSAU",
  GUYANA = "GUYANA",
  HAITI = "HAITI",
  HEARD_ISLAND_AND_MCDONALD_ISLANDS = "HEARD_ISLAND_AND_MCDONALD_ISLANDS",
  HOLY_SEE = "HOLY_SEE",
  HONDURAS = "HONDURAS",
  HONG_KONG = "HONG_KONG",
  HUNGARY = "HUNGARY",
  ICELAND = "ICELAND",
  INDIA = "INDIA",
  INDONESIA = "INDONESIA",
  IRAN = "IRAN",
  IRAQ = "IRAQ",
  IRELAND = "IRELAND",
  ISLE_OF_MAN = "ISLE_OF_MAN",
  ISRAEL = "ISRAEL",
  ITALY = "ITALY",
  JAMAICA = "JAMAICA",
  JAPAN = "JAPAN",
  JERSEY = "JERSEY",
  JORDAN = "JORDAN",
  KAZAKHSTAN = "KAZAKHSTAN",
  KENYA = "KENYA",
  KIRIBATI = "KIRIBATI",
  KOREA_NORTH = "KOREA_NORTH",
  KOREA_SOUTH = "KOREA_SOUTH",
  KUWAIT = "KUWAIT",
  KYRGYZSTAN = "KYRGYZSTAN",
  LAO_PEOPLES_DEMOCRATIC_REPUBLIC_THE = "LAO_PEOPLES_DEMOCRATIC_REPUBLIC_THE",
  LATVIA = "LATVIA",
  LEBANON = "LEBANON",
  LESOTHO = "LESOTHO",
  LIBERIA = "LIBERIA",
  LIBYA = "LIBYA",
  LIECHTENSTEIN = "LIECHTENSTEIN",
  LITHUANIA = "LITHUANIA",
  LUXEMBOURG = "LUXEMBOURG",
  MACAO = "MACAO",
  MADAGASCAR = "MADAGASCAR",
  MALAWI = "MALAWI",
  MALAYSIA = "MALAYSIA",
  MALDIVES = "MALDIVES",
  MALI = "MALI",
  MALTA = "MALTA",
  MARSHALL_ISLANDS = "MARSHALL_ISLANDS",
  MARTINIQUE = "MARTINIQUE",
  MAURITANIA = "MAURITANIA",
  MAURITIUS = "MAURITIUS",
  MAYOTTE = "MAYOTTE",
  MEXICO = "MEXICO",
  MICRONESIA_FEDERATED_STATES = "MICRONESIA_FEDERATED_STATES",
  MINOR_OUTLYING_ISLANDS_US = "MINOR_OUTLYING_ISLANDS_US",
  MOLDOVA_THE_REPUBLIC = "MOLDOVA_THE_REPUBLIC",
  MONACO = "MONACO",
  MONGOLIA = "MONGOLIA",
  MONTENEGRO = "MONTENEGRO",
  MONTSERRAT = "MONTSERRAT",
  MOROCCO = "MOROCCO",
  MOZAMBIQUE = "MOZAMBIQUE",
  MYANMAR = "MYANMAR",
  NAMIBIA = "NAMIBIA",
  NAURU = "NAURU",
  NEPAL = "NEPAL",
  NETHERLANDS = "NETHERLANDS",
  NEW_CALEDONIA = "NEW_CALEDONIA",
  NEW_ZEALAND = "NEW_ZEALAND",
  NICARAGUA = "NICARAGUA",
  NIGER = "NIGER",
  NIGERIA = "NIGERIA",
  NIUE = "NIUE",
  NORFOLK_ISLAND = "NORFOLK_ISLAND",
  NORTH_MACEDONIA = "NORTH_MACEDONIA",
  NORTHERN_MARIANA_ISLANDS = "NORTHERN_MARIANA_ISLANDS",
  NORWAY = "NORWAY",
  OMAN = "OMAN",
  PAKISTAN = "PAKISTAN",
  PALAU = "PALAU",
  PALESTINE_STATE = "PALESTINE_STATE",
  PANAMA = "PANAMA",
  PAPUA_NEW_GUINEA = "PAPUA_NEW_GUINEA",
  PARAGUAY = "PARAGUAY",
  PERU = "PERU",
  PHILIPPINES = "PHILIPPINES",
  PITCAIRN = "PITCAIRN",
  POLAND = "POLAND",
  PORTUGAL = "PORTUGAL",
  PUERTO_RICO = "PUERTO_RICO",
  QATAR = "QATAR",
  REUNION = "REUNION",
  ROMANIA = "ROMANIA",
  RUSSIA = "RUSSIA",
  RWANDA = "RWANDA",
  SAINT_BARTHELEMY = "SAINT_BARTHELEMY",
  SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = "SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA",
  SAINT_KITTS_AND_NEVIS = "SAINT_KITTS_AND_NEVIS",
  SAINT_LUCIA = "SAINT_LUCIA",
  SAINT_MARTIN_FRENCH_PART = "SAINT_MARTIN_FRENCH_PART",
  SAINT_PIERRE_AND_MIQUELON = "SAINT_PIERRE_AND_MIQUELON",
  SAINT_VINCENT_AND_THE_GRENADINES = "SAINT_VINCENT_AND_THE_GRENADINES",
  SAMOA = "SAMOA",
  SAN_MARINO = "SAN_MARINO",
  SAO_TOME_AND_PRINCIPE = "SAO_TOME_AND_PRINCIPE",
  SAUDI_ARABIA = "SAUDI_ARABIA",
  SENEGAL = "SENEGAL",
  SERBIA = "SERBIA",
  SEYCHELLES = "SEYCHELLES",
  SIERRA_LEONE = "SIERRA_LEONE",
  SINGAPORE = "SINGAPORE",
  SINT_MAARTEN_DUTCH_PART = "SINT_MAARTEN_DUTCH_PART",
  SLOVAKIA = "SLOVAKIA",
  SLOVENIA = "SLOVENIA",
  SOLOMON_ISLANDS = "SOLOMON_ISLANDS",
  SOMALIA = "SOMALIA",
  SOUTH_AFRICA = "SOUTH_AFRICA",
  SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS",
  SOUTH_SUDAN = "SOUTH_SUDAN",
  SPAIN = "SPAIN",
  SRI_LANKA = "SRI_LANKA",
  SUDAN = "SUDAN",
  SURINAME = "SURINAME",
  SVALBARD_AND_JAN_MAYEN = "SVALBARD_AND_JAN_MAYEN",
  SWEDEN = "SWEDEN",
  SWITZERLAND = "SWITZERLAND",
  SYRIA = "SYRIA",
  TAIWAN = "TAIWAN",
  TAJIKISTAN = "TAJIKISTAN",
  TANZANIA = "TANZANIA",
  THAILAND = "THAILAND",
  TIMOR_LESTE = "TIMOR_LESTE",
  TOGO = "TOGO",
  TOKELAU = "TOKELAU",
  TONGA = "TONGA",
  TRINIDAD_AND_TOBAGO = "TRINIDAD_AND_TOBAGO",
  TUNISIA = "TUNISIA",
  TURKEY = "TURKEY",
  TURKMENISTAN = "TURKMENISTAN",
  TURKS_AND_CAICOS_ISLANDS = "TURKS_AND_CAICOS_ISLANDS",
  TUVALU = "TUVALU",
  UGANDA = "UGANDA",
  UKRAINE = "UKRAINE",
  UNITED_ARAB_EMIRATES = "UNITED_ARAB_EMIRATES",
  UNITED_KINGDOM = "UNITED_KINGDOM",
  UNITED_STATES_OF_AMERICA = "UNITED_STATES_OF_AMERICA",
  URUGUAY = "URUGUAY",
  UZBEKISTAN = "UZBEKISTAN",
  VANUATU = "VANUATU",
  VENEZUELA = "VENEZUELA",
  VIETNAM = "VIETNAM",
  VIRGIN_ISLANDS_BRITISH = "VIRGIN_ISLANDS_BRITISH",
  VIRGIN_ISLANDS_US = "VIRGIN_ISLANDS_US",
  WALLIS_AND_FUTUNA = "WALLIS_AND_FUTUNA",
  WESTERN_SAHARA = "WESTERN_SAHARA",
  YEMEN = "YEMEN",
  ZAMBIA = "ZAMBIA",
  ZIMBABWE = "ZIMBABWE",
}

export enum TaddyType {
  PODCASTSERIES = "PODCASTSERIES",
  PODCASTEPISODE = "PODCASTEPISODE",
  COMICSERIES = "COMICSERIES",
  COMICISSUE = "COMICISSUE",
  CREATOR = "CREATOR",
}

export enum TopChartsSource {
  APPLE_PODCASTS = "APPLE_PODCASTS",
}

export enum TopChartsType {
  GENRE = "GENRE",
  COUNTRY = "COUNTRY",
}

export enum SearchContentType {
  PODCASTSERIES = "PODCASTSERIES",
  PODCASTEPISODE = "PODCASTEPISODE",
  COMICSERIES = "COMICSERIES",
  CREATOR = "CREATOR",
}

export enum SearchMatchType {
  EXACT_PHRASE = "EXACT_PHRASE",
  MOST_TERMS = "MOST_TERMS",
  ALL_TERMS = "ALL_TERMS",
}

export enum SearchSortOrder {
  EXACTNESS = "EXACTNESS",
  POPULARITY = "POPULARITY",
}
